import { defineSidebarConfig } from "vuepress-theme-hope";

export default defineSidebarConfig({
  "/cloud/": ["intro", "tencentCloud", "alicloud", "aws", "summary"],
  "/kubernetes/": [
    "intro",
    "concepts",
    "design",
    {
      text: "部署 Kubernetes",
      collapsable: true,
      children: [
        "setup/",
        "setup/kubeadm",
        "setup/docker-desktop",
        "setup/systemd",
        "setup/dashboard",
      ],
    },
    {
      text: "Kubernetes 命令行 kubectl",
      collapsable: true,
      children: ["kubectl/"],
    },
  ],
  "/compose/": [
    "introduction",
    "v2",
    "install",
    "usage",
    "commands",
    "compose_file",
    "django",
    "rails",
    "wordpress",
    "lnmp",
  ],
  "/install/": [
    "ubuntu",
    "debian",
    "fedora",
    "centos",
    "raspberry-pi",
    // 'offline',
    "mac",
    "windows",
    "mirror",
    "experimental",
  ],
  "/cases/os/": [
    {
      text: "操作系统",
      collapsable: false,
      children: ["busybox", "alpine", "debian", "centos", "summary"],
    },
    {
      text: "在 IDE 中使用 Docker",
      collapsable: false,
      children: ["/ide/", "/ide/vsCode"],
    },
  ],
  "/cases/ci/": [
    "actions/",
    {
      text: "Drone",
      collapsable: true,
      children: ["drone/", "drone/install"],
    },
  ],

  "/": [
    "/",
    "/CHANGELOG",
    "/CONTRIBUTING",
    {
      text: "Docker 简介",
      collapsable: false,
      children: ["introduction/", "introduction/what", "introduction/why"],
    },
    {
      text: "基本概念",
      collapsable: false,
      children: [
        "basic_concept/",
        "basic_concept/image",
        "basic_concept/container",
        "basic_concept/repository",
      ],
    },
    {
      text: "使用镜像",
      collapsable: false,
      children: [
        "image/",
        "image/pull",
        "image/list",
        "image/rm",
        "image/commit",
        "image/build",
        "image/other.md",
        "image/internal.md",
      ],
    },
    {
      text: "Dockerfile",
      collapsable: true,
      children: [
        "image/dockerfile/",
        "image/dockerfile/copy",
        "image/dockerfile/add",
        "image/dockerfile/cmd",
        "image/dockerfile/entrypoint",
        "image/dockerfile/env",
        "image/dockerfile/arg",
        "image/dockerfile/volume",
        "image/dockerfile/expose",
        "image/dockerfile/workdir",
        "image/dockerfile/user",
        "image/dockerfile/healthcheck",
        "image/dockerfile/label",
        "image/dockerfile/shell",
        "image/dockerfile/onbuild",
        "image/dockerfile/references",
        "image/multistage-builds/",
        "image/multistage-builds/laravel",
        "image/manifest",
      ],
    },
    {
      text: "操作容器",
      collapsable: false,
      children: [
        "container/",
        "container/run",
        "container/daemon",
        "container/stop",
        "container/attach_exec",
        "container/import_export",
        "container/rm",
      ],
    },
    {
      text: "Docker 仓库",
      collapsable: false,
      children: [
        "repository/",
        "repository/dockerhub",
        "repository/registry",
        "repository/registry_auth",
        "repository/nexus3_registry",
      ],
    },
    {
      text: "数据管理",
      collapsable: false,
      children: [
        "data_management/",
        "data_management/volume",
        "data_management/bind-mounts",
      ],
    },
    {
      text: "使用网络",
      collapsable: false,
      children: [
        "network/",
        "network/port_mapping",
        "network/linking",
        "network/dns",
      ],
    },
    {
      text: "高级网络配置",
      collapsable: true,
      children: [
        "advanced_network/",
        "advanced_network/quick_guide",
        "advanced_network/access_control",
        "advanced_network/port_mapping",
        "advanced_network/bridge",
        "advanced_network/example",
        "advanced_network/config_file",
        "advanced_network/ptp",
      ],
    },
    {
      text: "Swarm mode",
      collapsable: true,
      children: [
        "swarm_mode/",
        "swarm_mode/overview",
        "swarm_mode/create",
        "swarm_mode/deploy",
        "swarm_mode/stack",
        "swarm_mode/secret",
        "swarm_mode/config",
        "swarm_mode/rolling_update",
      ],
    },
    {
      text: "安全",
      collapsable: true,
      children: [
        "security/",
        "security/kernel_ns",
        "security/control_group",
        "security/daemon_sec",
        "security/kernel_capability",
        "security/other_feature",
        "security/summary",
      ],
    },
    {
      text: "底层实现",
      collapsable: true,
      children: [
        "underly/",
        "underly/arch",
        "underly/namespace",
        "underly/cgroups",
        "underly/ufs",
        "underly/container_format",
        "underly/network",
      ],
    },
    {
      text: "Docker Buildx",
      collapsable: false,
      children: [
        "buildx/",
        "buildx/buildkit",
        "buildx/buildx",
        "buildx/multi-arch-images",
      ],
    },
    {
      text: "Etcd",
      collapsable: true,
      children: [
        "etcd/",
        "etcd/intro",
        "etcd/install",
        "etcd/cluster",
        "etcd/etcdctl",
      ],
    },
    {
      text: "Fedora CoreOS",
      collapsable: true,
      children: ["coreos/", "coreos/intro", "coreos/install"],
    },
    "podman/",
    "appendix/faq/",
    {
      text: "热门镜像介绍",
      collapsable: true,
      children: [
        "appendix/repo/",
        "appendix/repo/ubuntu",
        "appendix/repo/centos",
        "appendix/repo/nginx",
        "appendix/repo/php",
        "appendix/repo/nodejs",
        "appendix/repo/mysql",
        "appendix/repo/wordpress",
        "appendix/repo/mongodb",
        "appendix/repo/redis",
        "appendix/repo/minio",
      ],
    },
    {
      text: "Docker 命令",
      collapsable: true,
      children: [
        "appendix/command/",
        "appendix/command/docker",
        "appendix/command/dockerd",
      ],
    },
    "appendix/best_practices",
    "appendix/debug",
    "appendix/resources",
  ],
});
